"""added new attributes to users table

Revision ID: 085c857387aa
Revises: 631e429afe7e
Create Date: 2025-10-02 21:30:47.320447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085c857387aa'
down_revision: Union[str, Sequence[str], None] = '631e429afe7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_phone', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('user_address', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_address')
    op.drop_column('users', 'user_phone')
    # ### end Alembic commands ###
