"""add expiry column in Products table

Revision ID: 7af68fe84850
Revises: 73e6868b04e6
Create Date: 2025-09-24 18:37:41.051812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af68fe84850'
down_revision: Union[str, Sequence[str], None] = '73e6868b04e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_expiry')
    # ### end Alembic commands ###
